# Generated by Django 2.2.4 on 2019-09-28 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='User_Character',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('characterImage_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.CharacterImage')),
                ('user_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
