# Generated by Django 2.2.4 on 2019-10-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190930_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='mapx',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='mapy',
            new_name='longitude',
        ),
    ]
